Update format.yml

diff --git a/.github/workflows/format.yml b/.github/workflows/format.yml
--- a/.github/workflows/format.yml
+++ b/.github/workflows/format.yml
@@ -40,26 +40,27 @@ jobs:
       run: |
         echo "Linting failed. To resolve this issue, please run `npm run lint-fix` on your change."
         exit 1
-    - name: Get main lint count
-      id: main-lint-count
+    - name: Checkout Main
       uses: actions/checkout@v4
       with:
         ref: main
         fetch-depth: 0
+    - name: Get main lint count
+      id: main-lint-count
       run: |
         MAIN_LINT_COUNT=$(npm run lint | tail -n 2 | head -n 1 | awk '{print $2 + 0}')
         echo "main_count=$MAIN_LINT_COUNT" >> $GITHUB_OUTPUT
     - name: Compare Lint Counts
-        run: |
-          PR_COUNT=${{ steps.pr-lint-count.outputs.pr_count }}
-          MAIN_COUNT=${{ steps.main-lint-count.outputs.main_count }}
+      run: |
+        PR_COUNT=${{ steps.pr-lint-count.outputs.pr_count }}
+        MAIN_COUNT=${{ steps.main-lint-count.outputs.main_count }}
 
-          echo "PR Lint Count: $PR_COUNT"
-          echo "Main Lint Count: $MAIN_COUNT"
+        echo "PR Lint Count: $PR_COUNT"
+        echo "Main Lint Count: $MAIN_COUNT"
 
-          if [[ "$PR_COUNT" -gt "$MAIN_COUNT" ]]; then
-            echo "Error: PR lint count ($PR_COUNT) is greater than main branch lint count ($MAIN_COUNT)"
-            exit 1
-          else
-            echo "PR lint count is not greater than main branch lint count.  Success!"
-          fi
+        if [[ "$PR_COUNT" -gt "$MAIN_COUNT" ]]; then
+          echo "Error: PR lint count ($PR_COUNT) is greater than main branch lint count ($MAIN_COUNT)"
+          exit 1
+        else
+          echo "PR lint count is not greater than main branch lint count.  Success!"
+        fi
